#! /usr/bin/env python
# =============================================
# Contact: <imaclim.r.world@gmail.com>
# Licence: AGPL-3.0
# Authors:
#     Florian Leblanc, Nicolas Graves
#     (CIRED - CNRS/AgroParisTech/ENPC/EHESS/CIRAD)
# =============================================


# This file is designed to treat, format and export IMF data on balance of paiement

############
###libraries
############
import pandas as pd
import numpy as np
import csv
import sys
import os
import copy
import common_cired
import aggregation_GTAP
import collections
from IPython.display import display
import argparse
from common_pandas_utils import df_set_column_values_as_columns_indexes
from common_pandas_utils import df_set_columns_indexes_as_column_values

# default parameters
year=2014

output_folder='./results/'
if not os.path.exists(output_folder):
    os.mkdir(output_folder)

# data locations
WBPath = sys.argv[1]
GTAPpath = '/data/shared/GTAP/'
Imaclim2ISO3_path = '/data/public_data/regional_aggregations/imaclim/'

if len(sys.argv) == 3:
    path_imf_data=sys.argv[1]
else:
    print("argument are ill-defined, using default arguments")
    path_imf_data='/data/public_data/IMF_web/BOP/'

# load data
df =  pd.read_csv( path_imf_data + "BOP_02-23-2022 22-48-47-98_timeSeries.csv",delimiter=',',header=0) #.set_index(0)

# load dict
# loading dict to match gtap with iso3
ISO2GTAP = pd.read_csv(GTAPpath+'./ISO3166_GTAP.csv')[['ISO','REG_V10']]
ISO2GTAP['ISO3'] = ISO2GTAP['ISO'].apply(lambda x: x.upper())
ISO2GTAP_dict = ISO2GTAP.set_index('ISO3')['REG_V10'].to_dict()

# if the converstion from Imaclim to ISO does not exist, create it
# TODO : should be dependent of aggregation rules, add a suffix to the file
if not os.path.isfile( Imaclim2ISO3_path + './imaclim_ISO3_aggregates.csv'):
    # small snippet of code, have been used to define actual ImaclimR regional agregation
    ISO2GTAP['Im_region'] = list(map(lambda x : GTAP10_2_Imaclim[x] if x !='xtw' else np.nan, ISO2GTAP['REG_V10']))
    ISO2GTAP[['ISO3','Im_region']].to_csv('/data/public_data/regional_aggregations/imaclim/imaclim_ISO3_aggregates.csv', sep='|', index=None)
# loading dict to match imaclim with iso3 (originally generated by the previous snippet)
ISO2Imaclim = pd.read_csv(Imaclim2ISO3_path + './imaclim_ISO3_aggregates.csv', sep='|')
ISO2Imaclim_dict = ISO2Imaclim.set_index('ISO3')['Im_region'].to_dict()

ISO2name = pd.read_csv(GTAPpath+'./ISO3166_GTAP.csv')[['ISO','CountryName']]

IMF_country_name2ISO=pd.read_csv(path_imf_data + "../extracted/country_codes/imf-weo-master/data/country.csv")
IMF_country_dict=IMF_country_name2ISO.set_index('WEO')['ISO'].to_dict()


# IMF dict
dict_bop_balance = {"BMIP_BP6_USD":"Current Account, Primary Income, Debit, US Dollars", "BMIS_BP6_USD":"Current Account, Secondary Income, Debit, US Dollars", "BK_DB_BP6_USD":"Capital Account, Total, Debit, US Dollars", "BFDLXF_BP6_USD":"Supplementary Items, Direct Investment, Net Incurrence of Liabilities (Excluding Exceptional Financing), US Dollars", "BFPLXF_BP6_USD":"Supplementary Items, Portfolio Investment, Net Incurrence of Liabilities (Excluding Exceptional Financing), US Dollars", "BFFL_BP6_USD":"Financial Account, Financial Derivatives (Other Than Reserves) and Employee Stock Options, Net Incurrence of Liabilities, US Dollars", "BFOLXF_BP6_USD":"Supplementary Items, Other Investment: Net Incurrence of Liabilities, Debt Instruments, Of which: Other Financial Corporations Of which: Other Financial Corporations (Excluding Exceptional Financing), US Dollars", "BXIP_BP6_USD":"Current Account, Primary Income, Credit, US Dollars", "BXIS_BP6_USD":"Current Account, Secondary Income, Credit, US Dollars", "BK_CD_BP6_USD":"Capital Account, Total, Credit, US Dollars", "BFDA_BP6_USD":"Financial Account, Net Lending (+) / Net Borrowing (-) (Balance from Financial Account), Direct Investment, Net Acquisition of Financial Assets, US Dollars", "BFPA_BP6_USD":"Financial Account, Portfolio Investment, Net Acquisition of Financial Assets, US Dollars", "BFFA_BP6_USD":"Financial Account, Financial Derivatives (Other Than Reserves) and Employee Stock Options, Net Acquisition of Financial Assets, US Dollars", "BFOA_BP6_USD":"Financial Account, Other Investment, Net Acquisition of Financial Assets, US Dollars"}

dict_goods_balance = {"BXG_BP6_USD":"Current Account, Goods and Services, Goods, Credit, US Dollars", "BMG_BP6_USD":"Current Account, Goods and Services, Goods, Debit, US Dollars", "BXS_BP6_USD":"Current Account, Goods and Services, Services, Credit, US Dollars", "BMS_BP6_USD":"Current Account, Goods and Services, Services, Debit, US Dollars"}

dict_bop_balance.update(dict_goods_balance)

dict_capital_export = {}
dict_capital_import = {}
dict_good = {}

for key, val in dict_bop_balance.items():
    if (not "Goods" in val) and ( ("Debit" in val or "Assets" in val)):
        dict_capital_export[key] = val
    if (not "Goods" in val) and ( ("Credit" in val or "Liabilities" in val)):
        dict_capital_import[key] = val
    if ("Good" in val):
        dict_good[key] = val

list_bop_capital_balance = list(dict_capital_export.keys()) + list(dict_capital_import.keys()) + list(dict_good.keys())

#-----------------------------------------------
# pretreatment dataframe

# select only Value
df = df[ df["Attribute"] == "Value"]

# Warning: yearly value and quater value have the same "Indicator Code" name
# we select only year values

list_col_year=[elt for elt in df.columns if elt.isdigit()]

df = df.iloc[ np.where( df[list_col_year].notna().sum(axis=1) != 0)[0]] 

#-----------------------------------------------
# data analysis dataframe

list_region = list(set( df['Country Name']))
list_region_code = list(set( df['Country Code']))

country_dict_df = df.set_index('Country Code')['Country Name'].to_dict()

# check whether each IMF country has an ISO

missing_reg_code = [code for code in list_region_code if not code in IMF_country_name2ISO['WEO'].values]
missing_reg_in_rule = [country_dict_df[code] for code in missing_reg_code]

# manual completion
dict_completion= {'China, P.R.: Macao':'MAC', 'Andorra, Principality of':'AND', 'Faroe Islands':'FRO', 'Eastern Caribbean Currency Union':'XCD', 'Anguilla':'AIA', 'Bermuda':'BMU', 'Nauru, Rep. of':'NRU', 'New Caledonia':'NCL', 'Montserrat':'MSR', 'Sint Maarten, Kingdom of the Netherlands':'SXM', 'Netherlands Antilles':'ANT', 'Curaçao, Kingdom of the Netherlands':'CUW', 'French Polynesia':'PYF', 'Cayman Islands':'CYM', 'Turks and Caicos Islands':'TSA'}
# dimissed: 'Euro Area' / 'Aruba, Kingdom of the Netherlands' / 'Curaçao and Sint Maarten' / 'West Bank and Gaza'

for code, name in country_dict_df.items():
    if name in dict_completion.keys():
        IMF_country_dict[code] = dict_completion[name]


# Check whether each ISO is associated to an Imaclim region
missing_iso = [reg for reg in IMF_country_dict.values() if not reg in ISO2Imaclim_dict.keys()]
missing_iso_bycode = [code for code in IMF_country_dict.keys() if not IMF_country_dict[code] in ISO2Imaclim_dict.keys()]

missing_iso_byname = [country_dict_df[code] for code in missing_iso_bycode]

dict_completion= {'SSD':'AFR', 'UVK':'EUR', 'CUW':'EUR', 'XCD': 'x', 'SXM': 'EUR', 'TSA':'EUR'}
#['South Sudan, Rep. of', 'Kosovo, Rep. of', 'Curaçao, Kingdom of the Netherlands', 'Eastern Caribbean Currency Union', 'Sint Maarten, Kingdom of the Netherlands', 'Turks and Caicos Islands']
#['SSD', 'UVK', 'CUW', 'XCD', 'SXM', 'TSA']

ISO2Imaclim_dict.update(dict_completion)

IMFcode_2_Imaclim={}
for code, value in IMF_country_dict.items():
    IMFcode_2_Imaclim[str(code)] = ISO2Imaclim_dict[ value]

#-----------------------------------------------
# data formating

#select Country Code, Indicator Code, list_col_year
#sel indicator (create a dict positive negatif
#select country available in IMFcode_2_Imaclim
#year as row, indicator as column

#convert country code from float to string to facilitate dataframe manipulation
df['Country Code'] = df['Country Code'].astype(str)

df = df[ df['Country Code'].isin( IMFcode_2_Imaclim.keys())]

df = df[ ['Country Code', 'Indicator Code'] + list_col_year]

df = df[ df['Indicator Code'].isin( list_bop_capital_balance )]

pd_concat_list = list()
for elt_select in list_col_year:
    df_out = df[ [elt for elt in df.keys() if (not elt in list_col_year) or elt==elt_select]].rename(columns={ elt_select: 'value'})
    df_out['year'] = elt_select
    pd_concat_list.append( df_out)

df = pd.concat(pd_concat_list)

df = df_set_column_values_as_columns_indexes( df, column_name_as_index='Indicator Code', column_name_for_value='value')

df = df.fillna(0)

#-----------------------------------------------
# data analysing and pre-treatment

# check whether each country has the data, otherwise split the net (credit/debit) data

for elt in list_bop_capital_balance:
    print(len(list(set(df[ df[elt] !=0]['Country Code'].values))), ':', dict_bop_balance[elt])

#-----------------------------------------------
# data creation

df['Capital Export'] = 0
df['Capital Import'] = 0
df['Current account goods - credit'] = 0
df['Current account goods - debit'] = 0

for key, val in dict_good.items():
    if 'Credit' in val:
        df['Current account goods - credit'] += df[key].astype(float)
    if 'Debit' in val:
        df['Current account goods - debit'] -= df[key].astype(float)

for key, val in dict_capital_export.items():
    df['Capital Export'] -= df[key].astype(float)
for key, val in dict_capital_import.items():
    df['Capital Import'] += df[key].astype(float)

df['Total Debit'] = df['Capital Export'] + df['Current account goods - debit']
df['Total Credit'] = df['Capital Import'] + df['Current account goods - credit']

df['Balance'] = df['Total Debit']+df['Total Credit']


#-----------------------------------------------
# regional agregation and export
df['Region_Im'] = list(map(lambda x: IMFcode_2_Imaclim[x], df['Country Code']))

# ensure all numerical columns are floats
list_num_col = [c for c in df.columns if not c in ['Region_Im', 'year', 'Country Code']]
df = df.drop('Country Code', axis=1)
df[list_num_col] = df[list_num_col].astype(float)
df_im = df.groupby(['Region_Im', 'year']).sum()

df_im = df_im.reset_index()

df_im = df_im[ ['Region_Im', 'year','Capital Export','Capital Import']]

df_im = df_im[ df_im['Region_Im'] !='x']

df_im['partExpK partImpK ratio'] = df_im['Capital Export'].values / df_im['Capital Import'].values

for elt in ['partExpK partImpK ratio', 'Capital Export', 'Capital Import']:
    for year in list(set(df_im['year'])):
        df2export=df_im[ df_im['year']==year][ ['Region_Im',elt]]
        df2export.to_csv(output_folder+ elt.replace(' ','_')+year+'.csv', sep='|', index=False)

