#! /usr/bin/env python
# =============================================
# Contact: <imaclim.r.world@gmail.com>
# Licence: AGPL-3.0
# Authors:
#     Florian Leblanc, Nicolas Graves
#     (CIRED - CNRS/AgroParisTech/ENPC/EHESS/CIRAD)
# =============================================


# This file is designed to support the diagnosis of GTAP treatment of IEA data.
# Results and corresponding paragraphs are compiled in the file of the same name on the Google Drive folder ImaclimV2.
# A large part of the file is just a copy of the file comparaison_GTAP_AIE_Enerdata.py, which targets were broader originally.

############
###libraries
############
import pandas as pd
import numpy as np
import csv
import sys
import os
import copy
import common_cired
import aggregation_GTAP
import collections
from IPython.display import display
import argparse

list_year = np.arange(2001,2020+1,1)

# data locations
WBPath = sys.argv[1]
GTAPpath = '/data/shared/GTAP/'
Imaclim2ISO3_path = '/data/public_data/regional_aggregations/imaclim/'


# loading dict to match gtap with iso3
ISO2GTAP = pd.read_csv(GTAPpath+'./ISO3166_GTAP.csv')[['ISO','REG_V10']]
ISO2GTAP['ISO3'] = ISO2GTAP['ISO'].apply(lambda x: x.upper())
ISO2GTAP_dict = ISO2GTAP.set_index('ISO3')['REG_V10'].to_dict()

# if the converstion from Imaclim to ISO does not exist, create it
# TODO : should be dependent of aggregation rules, add a suffix to the file
if not os.path.isfile( Imaclim2ISO3_path + './imaclim_ISO3_aggregates.csv'):
    # small snippet of code, have been used to define actual ImaclimR regional agregation
    ISO2GTAP['Im_region'] = list(map(lambda x : GTAP10_2_Imaclim[x] if x !='xtw' else np.nan, ISO2GTAP['REG_V10']))
    ISO2GTAP[['ISO3','Im_region']].to_csv('/data/public_data/regional_aggregations/imaclim/imaclim_ISO3_aggregates.csv', sep='|', index=None)
# loading dict to match imaclim with iso3 (originally generated by the previous snippet)
ISO2Imaclim = pd.read_csv(Imaclim2ISO3_path + './imaclim_ISO3_aggregates.csv', sep='|')
ISO2Imaclim_dict = ISO2Imaclim.set_index('ISO3')['Im_region'].to_dict()


print('Loading WB GDP data')
# The following script imports all available GDP data in current US$ for "+str(year)+".
# The data variable to be used is GDP_WB.
# exec(open(WBPath+'import_WB_GDP_to_DataFrame.py').read())
os.system("mkdir -p ./tmpdir")

#list_var = ['GDP (constant 2010 US$)','GDP (current US$)','GDP, PPP (constant 2017 international $)','GDP, PPP (current international $)','Inflation, GDP deflator (annual %)','Inflation, consumer prices (annual %)']
list_var = ['GDP (current US$)','GDP, PPP (current international $)']

for year in list_year:
    WB_data=[]
    for var in list_var:
        var_out=var
        for elt in [" ", "$","(",")",","]:
            var_out=var_out.replace(elt,"")
        os.system(WBPath+"extract_variable.sh "+WBPath+"regularized/WDI_Data.csv '"+var+"' | grep '|"+str(year)+"|' | awk --field-separator='|' '{ print $2 "+'"|"'+" $6}' > ./tmpdir/"+var_out+"_"+str(year)+".csv")
        df =  pd.read_csv("./tmpdir/"+var_out+"_"+str(year)+".csv",delimiter='|',header=None).set_index(0)
        WB_data.append( df.reset_index().rename(columns = {1:var, 0:'ISO'}).set_index('ISO'))

    df_WB = pd.concat( WB_data, axis=1, join='inner')
    df_WB = df_WB.reset_index()

    # data comparison
    wb_reg = list(df_WB['ISO'].values)

    # Apart from Kosovo, I check that the following are not country but aggregates in World Bank Data
    #Kosovo|XKX
    list2keep=[elt for elt in wb_reg if elt in ISO2Imaclim_dict.keys()]
    df_WB = df_WB[ df_WB['ISO'].isin(list2keep)]

    # data aggregation
    df_WB = df_WB.reset_index()
    df_WB['Region_Im'] = list(map(lambda x: ISO2Imaclim_dict[x], df_WB['ISO']))
    df_WB = df_WB.groupby(['Region_Im']).sum()

    df_WB.to_csv('world_bank_data_'+str(year)+'.csv', sep='|')

os.system("rm -r ./tmpdir")
